def load_all_plugins():
    import src.chunking.recursive
    import src.embeddings.sentence_transformers
    import src.embeddings.ollama
    import src.vectorstores.faiss_store
    import src.vectorstores.qdrant_store
    import src.retrieval.bm25
    import src.retrieval.dense_faiss
    import src.retrieval.dense_Qdrant
    import src.retrieval.hybrid
    import src.reranking.cross_encoder
    import src.reranking.identity
    import src.context.simple
    import src.generation.ollama
